"""add soft delete to employees

Revision ID: 0813d63bc13f
Revises: ccde7606b3f9
Create Date: 2026-08-30 15:47:20.827089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0813d63bc13f'
down_revision: Union[str, Sequence[str], None] = 'ccde7606b3f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_employees_deleted_at'), 'employees', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_deleted_at'), table_name='employees')
    op.drop_column('employees', 'deleted_at')
    # ### end Alembic commands ###
