"""create record history table

Revision ID: 6cf9d08c3c09
Revises: e57aa42550eb
Create Date: 2026-08-31 22:18:25.473388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cf9d08c3c09'
down_revision: Union[str, Sequence[str], None] = 'e57aa42550eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_history_changed_at'), 'record_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_record_history_resource'), 'record_history', ['resource'], unique=False)
    op.create_index(op.f('ix_record_history_resource_id'), 'record_history', ['resource_id'], unique=False)
    op.create_index(op.f('ix_record_history_user_id'), 'record_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_record_history_user_id'), table_name='record_history')
    op.drop_index(op.f('ix_record_history_resource_id'), table_name='record_history')
    op.drop_index(op.f('ix_record_history_resource'), table_name='record_history')
    op.drop_index(op.f('ix_record_history_changed_at'), table_name='record_history')
    op.drop_table('record_history')
    # ### end Alembic commands ###
